<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>smv</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^MODULE.*$</string>
	<key>foldingStopMarker</key>
	<string>^$</string>
	<key>keyEquivalent</key>
	<string>^~N</string>
	<key>name</key>
	<string>NuSVM</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.nusmv</string>
				</dict>
			</dict>
			<key>match</key>
			<string>--.*</string>
			<key>name</key>
			<string>comment.line.double-hyphen.nusmv</string>
		</dict>
		<dict>
			<key>match</key>
			<string>MODULE [a-zA-Z0-9_]*\s*\n</string>
			<key>name</key>
			<string>meta.function.section.module.nusmv</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>MODULE ([^(]+)\(([^)]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.function.section.module.name.nusmv</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.function.section.module.args.nusmv</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)\s*\n</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.predicatebraces.al</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.section.module.nusmv</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#functionscontent</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(VAR|ASSIGN|FAIRNESS|TRANS|INIT|DEFINE|CONSTANTS|IVAR|INVAR|SPEC|CTLSPEC|LTLSPEC|PSLSPEC|COMPUTE|INVARSPEC|JUSTICE|COMPASSION|ISA|CONSTRAINT|SIMPWFF|CTLWFF|LTLWFF|PSLWFF|COMPWFF)\b</string>
			<key>name</key>
			<string>meta.function.section.nusmv</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|!|&amp;|\||\bmod\b|\bunion\b|\bin\b|\bxor\b|\bxnor\b|-&gt;|&lt;-&gt;|=|!=|&lt;|&gt;|&lt;=|&gt;=|:=</string>
			<key>name</key>
			<string>keyword.operator.nusmv</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bboolean|array|of|integer|real|word|word1|bool|TRUE|FALSE|\d+\b</string>
			<key>name</key>
			<string>storage.nusmv</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\binit|next|EX|AX|EF|AF|EG|AG|E|F|O|G|H|X|Y|Z|A|U|S|V|T|BU|EBF|ABF|ABG\b</string>
			<key>name</key>
			<string>keyword.operator.nusmv</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bprocess|case|esac|self\b</string>
			<key>name</key>
			<string>keyword.control.nusmv</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[a-zA-Z_][a-zA-Z0-9_$#\\-]*\b</string>
			<key>name</key>
			<string>a.variable.nusmv</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.nusmv</string>
	<key>uuid</key>
	<string>3D68E7DB-D6AD-4437-AB57-9974DFBB9BE4</string>
</dict>
</plist>
